# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    # pack
    - name: Pack Stargazer.Common
      run: dotnet pack ./Stargazer.Common -c Release -p:PackageVersion=${{ github.ref_name }}
      
    # push to github
    - name: Push Stargazer.Common to github
      run: dotnet nuget push ./Stargazer.Common/bin/Release/Stargazer.Common.*.nupkg --api-key ${{ secrets.GIT_PAT }} --source "https://nuget.pkg.github.com/huangmingji/index.json"

    # push to nuget
    - name: Push Stargazer.Common to nuget
      run: dotnet nuget push ./Stargazer.Common/bin/Release/Stargazer.Common.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json
    